# Generated by Django 3.1.6 on 2021-11-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('person_name', models.CharField(max_length=250)),
            ],
        ),
    ]
