# Generated by Django 3.1.6 on 2021-11-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211123_2102'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mytest',
            table=None,
        ),
    ]
