# Generated by Django 3.1.6 on 2021-11-23 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211123_2108'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mytest',
            table='training"."my_test',
        ),
    ]
