# Generated by Django 3.1.6 on 2021-11-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211123_2121'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mytest',
            table=None,
        ),
    ]
